In [4]:
import pybryt
from reflecture import pybryt
from reflecture import pybryt_reference

import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [5]:
a = np.array([-1, 0, 1])

In [6]:
print(a)

print("Dimensions ", a.ndim)   # Number of dimensions
print("Shape      ", a.shape)  # number of elements in each dimension
print("Size       ", a.size)   # total number of elements
print("Data type  ", a.dtype)  # data type of element, 64 bit float (IEEE 754) by default

[-1  0  1]
Dimensions  1
Shape       (3,)
Size        3
Data type   int64


In [7]:
a = np.array( [1.1,2.2,3.3], np.float32)
print(a)
print("Data type", a.dtype)

a = np.array([1,2,3,4], np.float64)
print(a)
print("Data type", a.dtype)



[1.1 2.2 3.3]
Data type float32
[1. 2. 3. 4.]
Data type float64


In [8]:
mat = np.array( [[1,2,3], [4,5,6]] )
print(mat)
print("Dimensions: ", mat.ndim)
print("Size:       ", mat.size)
print("Shape:      ", mat.shape)

[[1 2 3]
 [4 5 6]]
Dimensions:  2
Size:        6
Shape:       (2, 3)


In [9]:
from pprint import pprint

pprint(mat)

array([[1, 2, 3],
       [4, 5, 6]])


In [10]:
alist = [[1, 2, 3], [4, 5, 6]]
mat = np.array(alist, complex)
pprint(mat)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])


In [11]:
a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
b = np.array([[[1, 1], [2, 2], [3, 3], [4, 4]], [[1, 1], [2, 2], [3, 3], [4, 4]],
              [[1, 1], [2, 2], [3, 3], [4, 4]]])

In [12]:
shape_a = (4,3)
shape_b = (3,4,2)

In [13]:
## The following code is used to check you solution and should not be modified
## It should help you by providing feedback to the solution you have provided
with pybryt.check(pybryt_reference(2, 21)):
    a
    shape_a

## The following code is used to check you solution and should not be modified
## It should help you by providing feedback to the solution you have provided
with pybryt.check(pybryt_reference(2, 22)):
    b
    shape_b



REFERENCE: exercise-2_21
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `a` checked: OK
  - SUCCESS: Correct number of columns and/or rows
REFERENCE: exercise-2_22
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `b` checked: OK
  - SUCCESS: Correct number of columns and/or rows


In [14]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(c.shape)
print("c[1][0][1]:", c[1][0][1]) # using index notation
print("c[1, 0, 1]:", c[1, 0, 1]) # using a tuple (more performant)

(2, 2, 2)
c[1][0][1]: 6
c[1, 0, 1]: 6


In [15]:
m = np.array([[1,1,2],[3,5,8],[13,21,34],[55,89,144]])
print(m)
m = m[:]
m[2:4, 1:3] = 1001
print(m)

[[  1   1   2]
 [  3   5   8]
 [ 13  21  34]
 [ 55  89 144]]
[[   1    1    2]
 [   3    5    8]
 [  13 1001 1001]
 [  55 1001 1001]]


In [16]:
# The following code is used to check your answer and should not be modified
with pybryt.check(pybryt_reference(2, 4)):
    m

REFERENCE: exercise-2_4
SATISFIED: True
MESSAGES:
  - SUCCESS: Great, you have succesfully affected the change to the array.


In [17]:
a = np.arange(6)
print("a = ")
pprint(a)
print("a.shape = ", a.shape, "\n")

# The new shape should be compatible with the old shape
a.shape = (3,2)
pprint(a)

# Or you can alter the size and shape of the array with resize().
# https://numpy.org/doc/stable/reference/generated/numpy.resize.html
mat = np.arange(6)
print("mat = ", mat)

mat1 = np.resize(mat, (3, 2))
print("mat1 = ", mat1)

mat2 = np.resize(mat, (3, 9))
print("mat2 = ", mat2)

mat3 = np.reshape(mat, (3, 2))
print("mat3 = ", mat3)



a = 
array([0, 1, 2, 3, 4, 5])
a.shape =  (6,) 

array([[0, 1],
       [2, 3],
       [4, 5]])
mat =  [0 1 2 3 4 5]
mat1 =  [[0 1]
 [2 3]
 [4 5]]
mat2 =  [[0 1 2 3 4 5 0 1 2]
 [3 4 5 0 1 2 3 4 5]
 [0 1 2 3 4 5 0 1 2]]
mat3 =  [[0 1]
 [2 3]
 [4 5]]


In [18]:
mat1.base is mat

False

In [19]:
a = np.arange(10).reshape([2,5])
b = np.arange(10).reshape([2,5])
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
-0.1*a
print(-0.1*a)

print(a+b)


[[-0.  -0.1 -0.2 -0.3 -0.4]
 [-0.5 -0.6 -0.7 -0.8 -0.9]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [21]:
a*b

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [22]:
a.dot(b.T)

array([[ 30,  80],
       [ 80, 255]])

In [23]:
def f(x):
    return x**3

x = np.array([1,2,3,4,5,6,7,8,9])
y = f(x)

print(y)

[  1   8  27  64 125 216 343 512 729]


In [24]:
A = np.array([
    [2,1,0],
    [-1,2,1],
    [0,-1,2]
])
print(A)

[[ 2  1  0]
 [-1  2  1]
 [ 0 -1  2]]


In [25]:
def f_02_06(x):
    (x**3) + (x * (np.exp(x))) + 1

In [26]:
f_02_06(A)

In [27]:
with pybryt.check(pybryt_reference(2, 6)):
    f_02_06(A)

REFERENCE: exercise-2_6
SATISFIED: False
MESSAGES:
  - Matrix `A` checked and it looks good.
  - ERROR: Your function returns the wrong solution. Check it, and try again.


In [28]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
a3 = np.concatenate((a1,a2),axis=1)
print(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [29]:
np.split(a3,1,axis=0)
print(a3)
np.ravel(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


array([ 1,  2,  3,  7,  8,  9,  4,  5,  6, 10, 11, 12])

In [30]:
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [31]:
a4 = np.concatenate((a1, a2), axis=0)
print(a4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
with pybryt.check(pybryt_reference(2, 7)):
    a1
    a2
    a4

REFERENCE: exercise-2_7
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `a1` check: OK.
  - SUCCESS: Array `a2` check: OK.
  - SUCCESS: Super! Array `a4` appears as expected.


In [33]:
p = np.array([[0, 1, 2],[3, 4, 5],[6, 7,8],[9, 10, 11]])
pprint(p)

rows = [0, 0, 3, 3]   # indices for rows
cols = [0, 2, 0, 2]   # indices for columns
q = p[rows, cols]
print(q)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
[ 0  2  9 11]


In [34]:
print(q.base is p)

False


In [35]:
m = np.array([[0, -1, 4, 20, 99], [-3, -5, 6, 7, -10]])
print(m)
print(m[m < 0])

[[  0  -1   4  20  99]
 [ -3  -5   6   7 -10]]
[ -1  -3  -5 -10]


In [36]:
a = np.arange(10)
print(a)
mask = np.ones(len(a), dtype=bool)
mask[[0,2,4]] = False  # set certain mask values to False
result = a[mask]

[0 1 2 3 4 5 6 7 8 9]


In [37]:
pprint(result)

array([1, 3, 5, 6, 7, 8, 9])


In [38]:
a = np.arange(10)
print(a)

def f_02_09(a):
    mask = np.ones(len(a), dtype=bool)
    mask[[3,5,9]] = False
    return a[mask]

f_02_09(a)
print(f_02_09(a))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 4 6 7 8]


In [39]:
with pybryt.check(pybryt_reference(2, 9)):
    print(f_02_09(a))

[0 1 2 4 6 7 8]
REFERENCE: exercise-2_9
SATISFIED: True
MESSAGES:
  - SUCCESS: You are using the correct input parameter to test your function.
  - SUCCESS: Great! Your function returns the correct result.


In [40]:
# Accessing a 2d array
nd = np.arange(100).reshape((10,10))

# accessing element of 2d array
%timeit -n 10000000 -r 3 nd[5][5]
%timeit -n 10000000 -r 3 nd[5,5]

157 ns ± 1.22 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)
84.3 ns ± 0.204 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)


In [ ]:
# Multiplying two vectors
x = np.arange(10E7)
%timeit -n 1 -r 10 x*x
%timeit -n 1 -r 10 x**2

198 ms ± 40.7 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [39]:
import matplotlib
print(matplotlib.rcsetup.all_backends)

%matplotlib inline

#%matplotlib widget

/var/folders/5_/xk1_mg_j3w36ptjv7xx4l5ym0000gp/T/ipykernel_48384/616687418.py:2: MatplotlibDeprecationWarning: The all_backends attribute was deprecated in Matplotlib 3.9 and will be removed in 3.11. Use ``matplotlib.backends.backend_registry.list_builtin()`` instead.
  print(matplotlib.rcsetup.all_backends)


['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']


In [40]:
import matplotlib
print(matplotlib.rcsetup.all_backends)


['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']


In [5]:
%matplotlib widget
import matplotlib.pyplot as plt

from scipy import interpolate as sitp
from scipy.interpolate import lagrange

# Invent some raw data 
x=np.array([0.5,2.0,4.0,5.0,7.0,9.0])
y=np.array([0.5,0.4,0.3,0.1,0.9,0.8])

## scipy.interpolate returns a numpy.poly1d instance
lp=sitp.lagrange(x, y)

xx= np.linspace(0.4, 9.1, 100)
fig = plt.figure()
plt.plot(x,y, "o", xx, lp(xx))
plt.show()

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


NameError: name 'np' is not defined

In [1]:
import scipy
print(scipy.__file__)


None


In [2]:
import matplotlib.pyplot as plt

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [3]:
import numpy as np
%matplotlib widget
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
z = np.sin(x+np.pi/2)